version: "3"

services:
  jekyll_custom:
    build: .
    image: al-folio-local-docker
    container_name: al-folio-local-website
    # Ensure gems are installed at container start, then serve the site.
    command: bash -c "\
      bundle config set --local path 'vendor/bundle' && \
      bundle install --jobs=4 --retry=3 && \
      bundle exec jekyll serve --watch --port=8080 --host=0.0.0.0 --livereload --verbose --trace"
    ports:
      # Host port is configurable via the PORT environment variable (default 8080)
      - "${PORT:-8080}:8080"
    volumes:
      - .:/srv/jekyll